FROM nodered/node-red:2.2.3
RUN cd
RUN npm i passport openid-client node-red
RUN cd /data && npm i node-red-contrib-influxdb
COPY settings.js /settings.js
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
